export type Skill = {
  id: string;
  name: string;
  grade: string;
  op: string;
  tip: string;
  level: number;
  run: number;
  high_score: number;
  wins: number;
  seconds: number;
};
export type Home = {
  learner: { display_name: string; age: number; daily_streak: number };
  today: string;
  comeback: { due: boolean; days_away: number; freeze_available: boolean };
  run_to_unlock: number;
  max_level: number;
  story_missions_enabled: boolean;
  guardian_consent_ai?: boolean;
  skills: Skill[];
};
export type Preferences = {
  sound: boolean;
  motion: boolean;
  contrast: boolean;
};
export type Problem = {
  id: string;
  skill_id: string;
  level: number;
  op: string;
  a: number;
  b: number;
  prompt: string;
  story?: string;
};
export type Provenance = {
  provider: string;
  prompt_version: string;
  fields_sent: string[];
  checks: { name: string; passed: boolean; detail?: string }[];
  final_source: string;
};
export type ArithmeticAssessment = {
  problem_id: string;
  correct: boolean;
  expected_answer: number;
  used_hint: boolean;
  level: number;
  run: number;
  unlocked: boolean;
  hearts_remaining?: number | null;
  round_ended?: boolean;
  ended_reason?: "completed" | "hearts" | null;
  answered?: number;
  total?: number;
  score?: number;
  bonus_points?: number;
  bonus_deadline_at?: number | null;
  server_now?: number;
};
export type ArithmeticFinish = {
  round_id: string;
  score: number;
  base_score?: number;
  bonus_points?: number;
  correct: number;
  total: number;
  answered?: number;
  hearts_total?: number | null;
  hearts_remaining?: number | null;
  ended_reason?: "completed" | "hearts" | null;
  level?: number;
};
export type ArithmeticRound = {
  practice_only?: boolean;
  round_id: string;
  level: number;
  problems: Problem[];
  current_level?: number;
  run?: number;
  hearts_total?: number | null;
  hearts_remaining?: number | null;
  bonus_seconds?: number | null;
  bonus_deadline_at?: number | null;
  server_now?: number;
  answered?: number;
  total?: number;
  score?: number;
  bonus_points?: number;
  round_ended?: boolean;
  ended_reason?: "completed" | "hearts" | null;
  assessments?: ArithmeticAssessment[];
  hinted_problem_ids?: string[];
  result?: ArithmeticFinish | null;
};
